//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardRecordsWithDoctorNameView
    {
        public int RecordNumber { get; set; }
        public System.DateTime RecordDate { get; set; }
        public string Diaghosis { get; set; }
        public string FIO { get; set; }
    }
}
