//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardRecordMedicalTest
    {
        public int Id { get; set; }
        public Nullable<int> CardRecordID { get; set; }
        public Nullable<int> MedicalTestID { get; set; }
    
        public virtual CardRecord CardRecord { get; set; }
        public virtual MedicalTest MedicalTest { get; set; }
    }
}
