//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalTest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MedicalTest()
        {
            this.CardRecordMedicalTest = new HashSet<CardRecordMedicalTest>();
        }
    
        public int Id { get; set; }
        public string TestName { get; set; }
        public decimal Price { get; set; }
        public string Info { get; set; }
        public int ClinicEmployeeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CardRecordMedicalTest> CardRecordMedicalTest { get; set; }
        public virtual ClinicEmployee ClinicEmployee { get; set; }
    }
}
